# Generated by Django 4.0.3 on 2022-03-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iloveshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilovemodels',
            name='image',
            field=models.URLField(default='../assets/nodata.jpg'),
            preserve_default=False,
        ),
    ]
