# Generated by Django 4.0.3 on 2022-03-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iloveshop', '0002_ilovemodels_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilovemodels',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
